### ISSUE TITLE
code

### ISSUE THREAD

**Issue by YantaiYang-05** [NiaLiu/ATT#1]
I found your paper, "Dataset Distillation by Automatic Training Trajectories," highly insightful. Could you please share the code mentioned for public release? It would significantly aid my research on extending your work to new datasets and architectures.

Thank you for considering my request.

**Comment by NiaLiu** [comment]
Hi Hiter-Q, highly appreciate your work (SRe2L) :)👍. Thanks for reminding me on uploading the code!

NiaLiu
